# Generated by Django 5.0.4 on 2024-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='user',
            name='inviter_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='код пригласившего'),
        ),
    ]
